### ISSUE TITLE
trimOnSave trims _after_ save instead of before

### ISSUE THREAD

**Issue by nkkollaw** [shardulm94/vscode-trailingspaces#24]
I think this is what the problem is.

I have trimOnSave on, and when I hit save it does trim whitespace, but it modifies the file and I have to hit save again.

**Comment by ameily** [comment]
I'm seeing this as well and it's pretty annoying. This must be a recent change since I don't remember having to save twice for the trimmed file to actually be saved to disk.

**Comment by nkkollaw** [comment]
Not sure, the repo hasn't been touched in 3 years. Something happened, though. Probably not a change in the plugin but in some other API.

**Comment by ameily** [comment]
I tracked the problem down. @nkkollaw I think you're right, something internal to VSCode API changed.

The problem is here: https://github.com/shardulm94/vscode-trailingspaces/blob/master/src/trailing-spaces/trailing-spaces.ts#L115. The call to `this.deleteTrailingSpaces` is not waited on, which is causing the trim operation to occur *after* the call to `document.save()`, which returns `false` because the document isn't dirty.

Unfortunately, I don't know enough about VScode extensions to submit a PR. I wrote a quick fix locally to verify I could fix the problem but I don't know the implications for my fix since I don't know the vscode api.

**Comment by ameily** [comment]
Ok, I lied, I submited a PR. If this project doesn't have an maintainer then I'll consider forking and maintaining it myself.

**Comment by nkkollaw** [comment]
https://goo.gl/images/3mnmiv

Awesome job, man! It drove me crazy.

**Comment by shardulm94** [comment]
@nkkollaw You can test this out with the beta release which uses the new VSCode API to applying pre-save edits.
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc3
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by nkkollaw** [comment]
Works great, man! Good job! :-)
